# Generated by Django 4.0.4 on 2022-05-31 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_order.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='nom complet')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=10, validators=[simple_order.base.models.phone_validator], verbose_name='téléphone')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('delivery_date', models.DateField(unique=True, verbose_name='date de livraison')),
            ],
            options={
                'verbose_name': 'livraison',
                'verbose_name_plural': 'livraisons',
                'ordering': ['-delivery_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer', verbose_name='client')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.delivery', verbose_name='livraison')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('label', models.CharField(max_length=300, unique=True, verbose_name='label')),
                ('price', models.FloatField(default=0, verbose_name='prix')),
                ('available', models.BooleanField(blank=True, default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['label', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order', verbose_name='commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'produits commandés',
                'verbose_name_plural': 'produits commandés',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='base.OrderedProduct', to='base.product', verbose_name='produits commandés'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'delivery')},
        ),
    ]
